using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.Networking;

// Generated by the Warboard v35 structural refactor.
// Method bodies were moved verbatim from GameController.cs.
public partial class GameController : MonoBehaviour
{
    private void ClearMissionBattlefield()
    {
        foreach (ObjectiveController objective
            in objectives.ToList())
        {
            if (objective != null)
                Destroy(objective.gameObject);
        }

        objectives.Clear();

        TerrainFeature[] terrain =
            Object.FindObjectsByType<
                TerrainFeature
            >();

        foreach (TerrainFeature feature
            in terrain)
        {
            if (feature != null)
                Destroy(feature.gameObject);
        }

        foreach (string outlineName
            in new[]
            {
                "Player 1 Deployment",
                "Player 2 Deployment",
                "Mission Exclusion"
            })
        {
            GameObject outline =
                GameObject.Find(
                    outlineName
                );

            if (outline != null)
                Destroy(outline);
        }
    }

    private void ApplyMissionBattlefieldLayout(
        int layoutIndex)
    {
        ClearMissionBattlefield();

        missionLayoutIndex =
            Mathf.Clamp(
                layoutIndex,
                1,
                3
            );

        activeMissionBattlefield =
            MissionBattlefieldRegistry.Build(
                missionDispositionPlayerOne,
                missionDispositionPlayerTwo,
                missionLayoutIndex,
                BoardWidth,
                BoardDepth
            );

        foreach (MissionObjectiveSpec spec
            in activeMissionBattlefield
                .Objectives)
        {
            MissionObjectiveRole role =
                spec.Role;

            if (spec.Role ==
                MissionObjectiveRole.PlayerOneHome)
            {
                role =
                    missionAttackerIndex == 0
                    ? MissionObjectiveRole
                        .PlayerOneHome
                    : MissionObjectiveRole
                        .PlayerTwoHome;
            }
            else if (spec.Role ==
                     MissionObjectiveRole.PlayerTwoHome)
            {
                role =
                    missionAttackerIndex == 0
                    ? MissionObjectiveRole
                        .PlayerTwoHome
                    : MissionObjectiveRole
                        .PlayerOneHome;
            }

            CreateMissionObjective(
                spec.Position,
                role
            );
        }

        foreach (MissionTerrainSpec spec
            in activeMissionBattlefield
                .Terrain)
        {
            CreateMissionTerrainFeature(
                spec
            );
        }

        BuildAndBindStandardTerrainAreas50(); // WARBOARD_V50_STANDARD_TERRAIN_AREAS

        CreateDeploymentZoneOutlines();

        Physics.SyncTransforms();
        RefreshObjectiveDisplays();
    }

    private void CreateMissionObjective(
        Vector3 position,
        MissionObjectiveRole role)
    {
        GameObject go =
            new GameObject(
                "Mission Objective"
            );

        ObjectiveController objective =
            go.AddComponent<
                ObjectiveController
            >();

        objective.Initialize(
            position,
            role
        );

        objectives.Add(
            objective
        );
    }

    private void CreateMissionTerrainFeature(
        MissionTerrainSpec spec)
    {
        if (spec == null)
            return;

        GameObject terrain =
            GameObject.CreatePrimitive(
                PrimitiveType.Cube
            );

        terrain.name =
            "MissionTerrain_" +
            spec.Id;

        terrain.transform.position =
            spec.Position;

        terrain.transform.localScale =
            spec.Size;

        TerrainFeature feature =
            terrain.AddComponent<
                TerrainFeature
            >();

        feature.Initialize(
            spec.Trait,
            spec.Id,
            spec.IsObjectiveArea
        );

        Color color =
            spec.Trait ==
                TerrainTrait.Blocking
            ? new Color(
                0.26f,
                0.26f,
                0.28f
            )
            : spec.Trait ==
                TerrainTrait.Cover
                ? new Color(
                    0.38f,
                    0.34f,
                    0.24f
                )
                : new Color(
                    0.22f,
                    0.34f,
                    0.22f
                );

        SetObjectColor(
            terrain,
            color
        );

        // WARBOARD_V45_MISSION_TERRAIN_STYLE
        WarboardV45Presentation.StyleTerrain(
            terrain,
            spec.Trait,
            spec.Id,
            spec.Size
        );
    }

    private void CreateCircularMissionOutline(
        string name,
        Vector2 centre,
        float radius,
        Color color)
    {
        GameObject go =
            new GameObject(name);

        LineRenderer line =
            go.AddComponent<
                LineRenderer
            >();

        line.loop = true;
        line.useWorldSpace = true;
        line.positionCount = 72;
        line.widthMultiplier = 0.07f;

        Shader shader =
            Shader.Find(
                "Sprites/Default"
            );

        if (shader != null)
            line.material =
                new Material(shader);

        line.startColor = color;
        line.endColor = color;

        for (int i = 0;
             i < line.positionCount;
             i++)
        {
            float angle =
                i /
                (float)line.positionCount *
                Mathf.PI *
                2f;

            line.SetPosition(
                i,
                new Vector3(
                    centre.x +
                        Mathf.Cos(angle) *
                        radius,
                    0.06f,
                    centre.y +
                        Mathf.Sin(angle) *
                        radius
                )
            );
        }
    }

    private string ObjectiveLiveState(
        ObjectiveController objective)
    {
        if (objective == null)
            return "Uncontrolled";

        Dictionary<string, int> totals =
            objective.ObjectiveControlTotals(
                squads
            );

        string controller =
            objective.Controller(
                squads
            );

        if (!string.IsNullOrWhiteSpace(
                controller))
        {
            return controller;
        }

        return totals.Count > 0
            ? "Contested"
            : "Uncontrolled";
    }

    private void RefreshObjectiveDisplays()
    {
        foreach (ObjectiveController objective
            in objectives)
        {
            if (objective == null)
                continue;

            objective.RefreshStatus(
                squads
            );

            string liveState =
                ObjectiveLiveState(
                    objective
                );

            string previous = "";

            bool known =
                objectiveLiveControl
                    .TryGetValue(
                        objective,
                        out previous
                    );

            objectiveLiveControl[
                objective] =
                liveState;

            if (known &&
                previous != liveState &&
                !deploymentMode &&
                round > 0)
            {
                AppendBattleLog(
                    "OBJECTIVE",
                    objective.name,
                    previous +
                    "  ->  " +
                    liveState
                );
            }
        }

        List<ObjectiveController> stale =
            objectiveLiveControl
                .Keys
                .Where(
                    objective =>
                        objective == null ||
                        !objectives.Contains(
                            objective
                        )
                )
                .ToList();

        foreach (ObjectiveController objective
            in stale)
        {
            objectiveLiveControl.Remove(
                objective
            );
        }
    }

    private void TryBeginSelectedMissionAction()
    {
        if (missionSystem == null ||
            selectedSquad == null)
        {
            status =
                "Select a unit before starting a mission action.";
            return;
        }

        SquadController unit =
            selectedSquad
                .JoinedActionController();

        MissionActionDefinition definition =
            missionSystem.PrimaryAction(
                unit.FactionId
            );

        if (definition == null)
        {
            status =
                "This Primary Mission has no unit-started Objective Action.";
            return;
        }

        string reason;

        if (!missionSystem.CanStartMissionAction(
                unit,
                out reason))
        {
            status = reason;
            return;
        }

        if (definition.TargetType ==
            MissionActionTargetType.None)
        {
            string result;

            missionSystem.StartMissionAction(
                unit,
                null,
                null,
                null,
                out result
            );

            status = result;
            RefreshMoveRing();
            return;
        }

        missionActionTargetingUnit =
            unit;

        missionActionTargetingDefinition =
            definition;

        showMissionPanel = false;

        string targetInstruction =
            definition.TargetType ==
                MissionActionTargetType.Objective
            ? "click a legal objective terrain area"
            : definition.TargetType ==
                MissionActionTargetType.EnemyUnit
                ? "click a legal enemy unit"
                : definition.TargetType ==
                    MissionActionTargetType
                        .OperationMarkerTerrain
                    ? "click terrain containing an opponent operation marker"
                    : "click a legal terrain area";

        status =
            definition.DisplayName +
            ": " +
            targetInstruction +
            ". ESC cancels.";
    }

    private string SelectedMissionActionButtonText()
    {
        if (missionSystem == null ||
            selectedSquad == null)
        {
            return "MISSION ACTION";
        }

        MissionActionDefinition definition =
            missionSystem.PrimaryAction(
                selectedSquad.FactionId
            );

        return
            definition == null
            ? "NO MISSION ACTION"
            : definition.DisplayName
                .ToUpper();
    }

    public bool MissionUnitIsEngaged(
        SquadController unit)
    {
        return
            unit != null &&
            IsEngaged(
                unit.JoinedActionController()
            );
    }

    public bool MissionUnitsHaveLineOfSight(
        SquadController source,
        SquadController target)
    {
        if (source == null ||
            target == null)
        {
            return false;
        }

        return
            JoinedModels(source)
                .Any(
                    model =>
                        model != null &&
                        ModelHasLineOfSight(
                            model,
                            target
                        )
                );
    }

    public bool IsHomeObjectiveForFaction(
        ObjectiveController objective,
        string faction)
    {
        if (objective == null ||
            factions.Count < 2)
        {
            return false;
        }

        return
            faction == factions[0]
            ? objective.MissionRole ==
                MissionObjectiveRole
                    .PlayerOneHome
            : objective.MissionRole ==
                MissionObjectiveRole
                    .PlayerTwoHome;
    }

    public bool IsOpponentHomeObjectiveForFaction(
        ObjectiveController objective,
        string faction)
    {
        if (objective == null ||
            factions.Count < 2)
        {
            return false;
        }

        return
            faction == factions[0]
            ? objective.MissionRole ==
                MissionObjectiveRole
                    .PlayerTwoHome
            : objective.MissionRole ==
                MissionObjectiveRole
                    .PlayerOneHome;
    }

    public bool UnitWithinAnyObjective(
        SquadController unit)
    {
        return objectives.Any(
            objective =>
                objective != null &&
                objective.UnitWithinRange(
                    unit
                )
        );
    }

    private float DistancePointToClosestObjective(
        Vector3 point)
    {
        float best =
            float.MaxValue;

        foreach (ObjectiveController objective
            in objectives)
        {
            if (objective == null)
                continue;

            best =
                Mathf.Min(
                    best,
                    HorizontalDistance(
                        point,
                        objective.transform.position
                    )
                );
        }

        return best;
    }

    private void CaptureObjectiveControlAtPhaseStart()
    {
        objectiveControlAtPhaseStart.Clear();

        foreach (ObjectiveController objective
            in objectives)
        {
            if (objective == null)
                continue;

            objectiveControlAtPhaseStart[objective] =
                objective.Controller(
                    squads
                );
        }
    }

    private void ApplyAeldariEndOfPhaseObjectiveRules()
    {
        if (aeldariRules == null)
            return;

        foreach (string faction
            in factions)
        {
            if (!aeldariRules.DetachmentIs(
                    faction,
                    AeldariDetachment.CorsairCoterie))
            {
                continue;
            }

            foreach (ObjectiveController objective
                in objectives)
            {
                if (objective == null ||
                    objective.Controller(
                        squads
                    ) != faction)
                {
                    continue;
                }

                bool voidThiefPresent =
                    squads.Any(
                        unit =>
                            unit != null &&
                            !unit.IsAttachedLeader &&
                            unit.FactionId ==
                                faction &&
                            unit.IsAlive &&
                            unit.IsOnBattlefield &&
                            unit.HasKeyword(
                                "anhrathe") &&
                            objective.UnitWithinRange(
                                unit
                            )
                    );

                if (!voidThiefPresent)
                    continue;

                objective.SecureFor(
                    faction
                );

                AppendBattleLog(
                    "AELDARI",
                    "Void Thieves",
                    objective.name +
                    " remains secured by " +
                    DisplayFactionName(
                        faction
                    ) +
                    " until the opponent exceeds its Level of Control at the end of a phase."
                );
            }
        }
    }

    public void AddPrimaryScore(
        string faction,
        int amount,
        int scoringRound = -1)
    {
        AddScore(
            faction,
            amount,
            scoringRound,
            true
        );
    }

    public void AddSecondaryScore(
        string faction,
        int amount,
        int scoringRound = -1)
    {
        AddScore(
            faction,
            amount,
            scoringRound,
            false
        );
    }

    public int AddPrimaryScoreCapped(
        string faction,
        int amount,
        int scoringRound)
    {
        if (amount <= 0)
            return 0;

        int roundRemaining =
            Mathf.Max(
                0,
                15 -
                RoundScore(
                    faction,
                    scoringRound,
                    true
                )
            );

        int gameRemaining =
            Mathf.Max(
                0,
                45 -
                TotalScoreType(
                    faction,
                    true
                )
            );

        int awarded =
            Mathf.Min(
                amount,
                roundRemaining,
                gameRemaining
            );

        AddScore(
            faction,
            awarded,
            scoringRound,
            true
        );

        return awarded;
    }

    public int AddSecondaryScoreCapped(
        string faction,
        int amount,
        int scoringRound,
        string fixedCard)
    {
        if (amount <= 0)
            return 0;

        int roundRemaining =
            Mathf.Max(
                0,
                15 -
                RoundScore(
                    faction,
                    scoringRound,
                    false
                )
            );

        int gameRemaining =
            Mathf.Max(
                0,
                45 -
                TotalScoreType(
                    faction,
                    false
                )
            );

        int fixedRemaining =
            amount;

        if (!string.IsNullOrWhiteSpace(
                fixedCard))
        {
            if (!fixedSecondaryScoreByCard
                .ContainsKey(
                    faction))
            {
                fixedSecondaryScoreByCard[
                    faction] =
                    new Dictionary<
                        string,
                        int
                    >();
            }

            int current = 0;

            fixedSecondaryScoreByCard[
                faction]
                .TryGetValue(
                    fixedCard,
                    out current
                );

            fixedRemaining =
                Mathf.Max(
                    0,
                    20 - current
                );
        }

        int awarded =
            Mathf.Min(
                amount,
                roundRemaining,
                gameRemaining,
                fixedRemaining
            );

        AddScore(
            faction,
            awarded,
            scoringRound,
            false
        );

        if (awarded > 0 &&
            !string.IsNullOrWhiteSpace(
                fixedCard))
        {
            Dictionary<string, int> cards =
                fixedSecondaryScoreByCard[
                    faction];

            if (!cards.ContainsKey(
                fixedCard))
            {
                cards[fixedCard] = 0;
            }

            cards[fixedCard] +=
                awarded;
        }

        return awarded;
    }

    private void AddScore(
        string faction,
        int amount,
        int scoringRound,
        bool primary)
    {
        if (string.IsNullOrWhiteSpace(
                faction) ||
            amount <= 0)
        {
            return;
        }

        if (scoringRound < 1)
        {
            scoringRound =
                Mathf.Max(
                    1,
                    round
                );
        }

        Dictionary<
            string,
            Dictionary<int, int>
        > source =
            primary
            ? primaryScoreByRound
            : secondaryScoreByRound;

        if (!source.ContainsKey(
            faction))
        {
            source[faction] =
                new Dictionary<int, int>();
        }

        Dictionary<int, int> rounds =
            source[faction];

        if (!rounds.ContainsKey(
            scoringRound))
        {
            rounds[scoringRound] = 0;
        }

        rounds[scoringRound] +=
            amount;

        if (!score.ContainsKey(
            faction))
        {
            score[faction] = 0;
        }

        score[faction] +=
            amount;
    }

    private int RoundScore(
        string faction,
        int scoringRound,
        bool primary)
    {
        Dictionary<
            string,
            Dictionary<int, int>
        > source =
            primary
            ? primaryScoreByRound
            : secondaryScoreByRound;

        Dictionary<int, int> rounds;

        if (!source.TryGetValue(
                faction,
                out rounds) ||
            rounds == null)
        {
            return 0;
        }

        int value;

        return rounds.TryGetValue(
            scoringRound,
            out value)
            ? value
            : 0;
    }

    private int TotalScoreType(
        string faction,
        bool primary)
    {
        Dictionary<
            string,
            Dictionary<int, int>
        > source =
            primary
            ? primaryScoreByRound
            : secondaryScoreByRound;

        Dictionary<int, int> rounds;

        if (!source.TryGetValue(
                faction,
                out rounds) ||
            rounds == null)
        {
            return 0;
        }

        return rounds.Values.Sum();
    }

    private string ScoreText()
    {
        return string.Join(
            "    ",
            factions.Select(
                faction =>
                    DisplayFactionName(
                        faction
                    ) +
                    ": " +
                    (score.ContainsKey(
                        faction)
                        ? score[faction]
                        : 0) +
                    " VP"
            ).ToArray()
        );
    }

    public int WorldUiRoundSecondary(
        int index,
        int scoringRound)
    {
        return RoundScore(
            WorldUiFactionId(
                index
            ),
            scoringRound,
            false
        );
    }

    public int WorldUiSecondaryTotal(
        int index)
    {
        return TotalScoreType(
            WorldUiFactionId(
                index
            ),
            false
        );
    }

    private MissionSecondaryMode
        NextSecondaryMode(
            MissionSecondaryMode value)
    {
        if (value ==
            MissionSecondaryMode.Tactical)
        {
            return
                MissionSecondaryMode.Fixed;
        }

        if (value ==
            MissionSecondaryMode.Fixed)
        {
            return
                MissionSecondaryMode.Manual;
        }

        return
            MissionSecondaryMode.Tactical;
    }

}
