using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.Networking;

// Generated by the Warboard v35 structural refactor.
// Method bodies were moved verbatim from GameController.cs.
public partial class GameController : MonoBehaviour
{
    // WARBOARD_V36_DIRECT_SETUP_EVENTS
    private MissionDeploymentZone
        DeploymentZoneForFaction(
            string faction)
    {
        if (activeMissionBattlefield == null)
            return null;

        return
            activeMissionBattlefield
                .ZoneForRole(
                    FactionUsesAttackerZone(
                        faction
                    )
                );
    }

    public bool MissionUnitWhollyWithinDeploymentZone(
        SquadController unit,
        string zoneFaction)
    {
        if (unit == null ||
            activeMissionBattlefield == null ||
            string.IsNullOrWhiteSpace(zoneFaction))
        {
            return false;
        }

        MissionDeploymentZone zone =
            DeploymentZoneForFaction(zoneFaction);

        if (zone == null)
            return false;

        List<ModelToken> models =
            unit.JoinedLivingModelTokens();

        if (models.Count == 0)
            return false;

        return models.All(
            model =>
                model != null &&
                zone.ContainsBase(
                    model.transform.position,
                    model.BaseRadiusInches
                )
        );
    }

    public bool MissionUnitWhollyWithinOpponentDeploymentZone(
        SquadController unit,
        string faction)
    {
        if (unit == null ||
            factions.Count < 2)
        {
            return false;
        }

        string opponent =
            factions.FirstOrDefault(
                value =>
                    value != faction
            );

        return
            !string.IsNullOrWhiteSpace(opponent) &&
            MissionUnitWhollyWithinDeploymentZone(
                unit,
                opponent
            );
    }

    private void CreateDeploymentZoneOutlines()
    {
        if (activeMissionBattlefield == null ||
            factions.Count < 2)
        {
            return;
        }

        CreateDeploymentPolygonOutline(
            "Player 1 Deployment",
            DeploymentZoneForFaction(
                factions[0]
            ),
            new Color(
                0.75f,
                0.25f,
                0.85f,
                1f
            )
        );

        CreateDeploymentPolygonOutline(
            "Player 2 Deployment",
            DeploymentZoneForFaction(
                factions[1]
            ),
            new Color(
                0.20f,
                0.90f,
                0.50f,
                1f
            )
        );

        if (activeMissionBattlefield
                .AttackerZone != null &&
            activeMissionBattlefield
                .AttackerZone
                .HasCircularExclusion)
        {
            CreateCircularMissionOutline(
                "Mission Exclusion",
                activeMissionBattlefield
                    .AttackerZone
                    .ExclusionCentre,
                activeMissionBattlefield
                    .AttackerZone
                    .ExclusionRadius,
                new Color(
                    0.92f,
                    0.82f,
                    0.32f,
                    0.85f
                )
            );
        }
    }

    private void CreateDeploymentPolygonOutline(
        string name,
        MissionDeploymentZone zone,
        Color color)
    {
        if (zone == null ||
            zone.Polygon.Count < 3)
        {
            return;
        }

        GameObject go =
            new GameObject(name);

        LineRenderer line =
            go.AddComponent<
                LineRenderer
            >();

        line.loop = true;
        line.useWorldSpace = true;
        line.positionCount =
            zone.Polygon.Count;
        line.widthMultiplier = 0.10f;

        Shader shader =
            Shader.Find(
                "Sprites/Default"
            );

        if (shader != null)
            line.material =
                new Material(shader);

        line.startColor = color;
        line.endColor = color;

        for (int i = 0;
             i < zone.Polygon.Count;
             i++)
        {
            Vector2 point =
                zone.Polygon[i];

            line.SetPosition(
                i,
                new Vector3(
                    point.x,
                    0.055f,
                    point.y
                )
            );
        }
    }

    private void LoadArmy(string resourcePath)
    {
        TextAsset asset =
            Resources.Load<TextAsset>(resourcePath);

        if (asset == null)
        {
            Debug.LogError(
                "Missing army JSON: Resources/" +
                resourcePath +
                ".json"
            );

            return;
        }

        ArmyData army =
            JsonUtility.FromJson<ArmyData>(asset.text);

        if (!factions.Contains(army.factionId))
            factions.Add(army.factionId);

        foreach (ArmyEntryData entry in army.units)
        {
            SpawnSquad(
                entry.unitResource,
                new Vector3(entry.x, 0f, entry.z)
            );
        }
    }

    private void BeginYellowScribeLoad(
        int playerIndex)
    {
        if (loadingYellowScribe)
            return;

        string code =
            playerIndex == 0
            ? yellowCodePlayerOne
            : yellowCodePlayerTwo;

        code =
            code == null
            ? ""
            : code.Trim();

        if (code.Length != 8)
        {
            status =
                "YellowScribe codes should be exactly 8 characters.";
            return;
        }

        StartCoroutine(
            LoadYellowScribeRoster(
                code,
                playerIndex
            )
        );
    }

    private IEnumerator LoadYellowScribeRoster(
        string code,
        int playerIndex)
    {
        loadingYellowScribe = true;

        status =
            "Loading YellowScribe roster " +
            code +
            "...";

        string url =
            YellowScribeEndpoint +
            UnityWebRequest.EscapeURL(
                code
            );

        using (UnityWebRequest request =
            UnityWebRequest.Get(url))
        {
            request.timeout = 20;

            yield return request.SendWebRequest();

            if (request.result !=
                UnityWebRequest.Result.Success)
            {
                loadingYellowScribe = false;

                status =
                    "YellowScribe request failed: " +
                    request.error +
                    ". If the code was created more than about 10 minutes ago, export a fresh one.";

                yield break;
            }

            string json =
                request.downloadHandler.text;

            YellowScribeImportResult imported;

            try
            {
                imported =
                    YellowScribeImporter.Parse(
                        json,
                        playerIndex == 0
                        ? "Player 1"
                        : "Player 2"
                    );
            }
            catch (
                System.Exception exception)
            {
                loadingYellowScribe = false;

                status =
                    "YellowScribe import failed: " +
                    exception.Message;

                yield break;
            }

            RemovePlayerArmy(
                playerIndex
            );

            string gameFactionId =
                playerIndex == 0
                ? "Player 1"
                : "Player 2";

            if (!factions.Contains(
                gameFactionId))
            {
                if (playerIndex == 0)
                    factions.Insert(
                        0,
                        gameFactionId
                    );
                else
                    factions.Add(
                        gameFactionId
                    );
            }

            int index = 0;

            foreach (UnitData unit
                in imported.Units)
            {
                // All imported models are staged for deployment immediately,
                // so these are only harmless temporary root positions.
                float x =
                    playerIndex == 0
                    ? -11f
                    : 11f;

                float z =
                    -9f +
                    (index % 8) *
                    2.4f;

                SpawnSquad(
                    unit,
                    new Vector3(
                        x,
                        0f,
                        z
                    )
                );

                index++;
            }

            if (playerIndex == 0)
            {
                playerOneLoaded = true;
                playerOneRosterLabel =
                    imported.SourceFaction;
            }
            else
            {
                playerTwoLoaded = true;
                playerTwoRosterLabel =
                    imported.SourceFaction;
            }

            loadingYellowScribe = false;

            status =
                "Loaded " +
                imported.Units.Count +
                " unit(s) for " +
                (playerIndex == 0
                    ? "Player 1"
                    : "Player 2") +
                " from YellowScribe" +
                (string.IsNullOrWhiteSpace(
                    imported.Edition)
                    ? ""
                    : " (" +
                      imported.Edition +
                      ")") +
                ". Imported weapon assignments: " +
                imported.ImportedRangedWeaponInstances +
                " ranged / " +
                imported.ImportedMeleeWeaponInstances +
                " melee. Multi-weapon combat is active.";
        }
    
        NotifyRostersChanged();
}

    private void RemovePlayerArmy(
        int playerIndex)
    {
        string faction =
            playerIndex == 0
            ? "Player 1"
            : "Player 2";

        List<SquadController> toRemove =
            squads
                .Where(
                    squad =>
                        squad.FactionId ==
                        faction
                )
                .ToList();

        foreach (SquadController squad
            in toRemove)
        {
            squads.Remove(squad);

            if (squad != null)
                Destroy(squad.gameObject);
        }

        factions.Remove(faction);

        if (playerIndex == 0)
            playerOneLoaded = false;
        else
            playerTwoLoaded = false;
    
        NotifyRostersChanged();
}

    private void OpenMissionSetup()
    {
        if (!playerOneLoaded ||
            !playerTwoLoaded)
        {
            status =
                "Load both players before mission setup.";
            return;
        }

        factions.Clear();
        factions.Add("Player 1");
        factions.Add("Player 2");

        if (squads.Any(
            squad =>
                squad.FactionId ==
                "Aeldari"))
        {
            factions.Clear();
            factions.Add("Aeldari");
            factions.Add("Necrons");
        }

        if (aeldariRules != null)
        {
            aeldariRules.Configure(
                squads,
                factions
            );
        }

        armyImportMode = false;
        missionSetupMode = true;
        deploymentMode = false;

        status =
            "Select both Force Dispositions, secondary modes and one of the three recommended-layout slots.";
    }

    private void FinishArmyLoading()
    {
        if (factions.Count < 2)
        {
            status =
                "Mission setup requires two loaded armies.";
            return;
        }

        score.Clear();
        primaryScoreByRound.Clear();
        secondaryScoreByRound.Clear();
        fixedSecondaryScoreByCard.Clear();
        commandPoints.Clear();

        foreach (string faction
            in factions)
        {
            score[faction] = 0;

            primaryScoreByRound[faction] =
                new Dictionary<int, int>();

            secondaryScoreByRound[faction] =
                new Dictionary<int, int>();

            fixedSecondaryScoreByCard[faction] =
                new Dictionary<string, int>();

            commandPoints[faction] = 0;
        }

        ApplyMissionBattlefieldLayout(
            missionLayoutIndex
        );

        missionSystem =
            new MissionSystem(
                this,
                squads,
                objectives,
                factions
            );

        missionSystem.Configure(
            missionDispositionPlayerOne,
            missionDispositionPlayerTwo,
            missionSecondaryPlayerOne,
            missionSecondaryPlayerTwo,
            missionLayoutIndex,
            missionAttackerIndex
        );

        factionRules.Configure(
            squads,
            factions
        );

        if (aeldariRules != null)
        {
            aeldariRules.Configure(
                squads,
                factions
            );

            foreach (string faction
                in factions)
            {
                aeldariRules.ApplyDetachmentKeywords(
                    faction,
                    squads
                );

                if (aeldariRules.IsAeldariFaction(
                        faction))
                {
                    AppendBattleLog(
                        "AELDARI",
                        aeldariRules.DetachmentName(
                            faction
                        ),
                        aeldariRules.RuleSummary(
                            faction
                        )
                    );
                }
            }
        }

        foreach (SquadController squad
            in squads)
        {
            squad.StageForDeployment();
        }

        missionSetupMode = false;
        deploymentMode = true;
        battleOver = false;
        battleSummary = "";

        BeginDeployment();
    }

    private void SetDeploymentWorldLabelsVisible(
        bool visible)
    {
        foreach (SquadController squad
            in squads)
        {
            if (squad == null)
                continue;

            foreach (ModelToken model
                in squad.AllLivingModelTokens())
            {
                if (model == null)
                    continue;

                model.SetWoundDisplayVisible(
                    visible &&
                    squad.IsOnBattlefield
                );
            }
        }
    }

    private void BeginDeployment()
    {
        if (!EnsureFactionControllersReadyForDeployment())
        {
            return;
        }


        deploymentMode = true;
        SetDeploymentWorldLabelsVisible(false);
        round = 0;
        phase = Phase.Command;
        activeFactionIndex =
            Mathf.Clamp(
                missionAttackerIndex,
                0,
                Mathf.Max(
                    0,
                    factions.Count - 1
                )
            );

        if (factions.Count == 0)
        {
            status = "No factions loaded.";
            return;
        }

        activeFaction =
            factions[activeFactionIndex];

        currentDeploymentSquad =
            FindNextUndeployedForFaction(
                activeFaction
            );

        deploymentRosterScroll =
            Vector2.zero;

        if (currentDeploymentSquad == null)
        {
            AdvanceDeploymentTurn();
            return;
        }

        UpdateDeploymentStatus();
    }

    private void ChooseDeploymentSquad(
        SquadController squad)
    {
        if (!deploymentMode ||
            squad == null ||
            squad.FactionId !=
                activeFaction ||
            squad.BattlefieldState !=
                SquadBattlefieldState.Undeployed)
        {
            return;
        }

        currentDeploymentSquad =
            squad;

        deploymentBodyguardChoiceIndex = 0;

        UpdateDeploymentStatus();
    }

    private void AdvanceDeploymentTurn()
    {
        if (!AnyUndeployedUnits())
        {
            BeginBattle();
            return;
        }

        for (int step = 1;
             step <= factions.Count;
             step++)
        {
            int index =
                (activeFactionIndex + step) %
                factions.Count;

            SquadController next =
                FindNextUndeployedForFaction(
                    factions[index]
                );

            if (next != null)
            {
                activeFactionIndex = index;
                activeFaction =
                    factions[index];

                currentDeploymentSquad =
                    next;

                deploymentRosterScroll =
                    Vector2.zero;

                UpdateDeploymentStatus();
                return;
            }
        }

        BeginBattle();
    }

    private void UpdateDeploymentStatus()
    {
        if (currentDeploymentSquad == null)
        {
            status =
                "No unit waiting for deployment.";
            return;
        }

        string zone =
            activeMissionBattlefield != null
            ? activeMissionBattlefield.DisplayName +
              " " +
              (FactionUsesAttackerZone(
                   activeFaction)
                  ? "ATTACKER deployment zone"
                  : "DEFENDER deployment zone")
            : "deployment zone";

        status =
            "DEPLOYMENT  -  " +
            ActiveFactionDisplayName() +
            ": selected " +
            currentDeploymentSquad.DisplayName +
            ". Choose any undeployed unit from the roster, then place it wholly inside the " +
            zone +
            " or send it to Reserves. " +
            (currentDeploymentSquad.IsLeaderUnit
                ? "LEADER unit: attach it to a compatible bodyguard in the roster, whether or not it has deployed yet, or deploy it separately."
                : (currentDeploymentSquad.HasDeepStrike
                    ? "This unit has Deep Strike."
                    : "This unit will use Strategic Reserves if reserved."));
    }

    private bool JoinedDeploymentFormationIsLegal(
        SquadController bodyguard,
        List<ModelToken> joined,
        string faction,
        out string failureReason)
    {
        failureReason = "";

        if (bodyguard == null ||
            joined == null ||
            joined.Count == 0)
        {
            failureReason =
                "the joined unit has no models";
            return false;
        }

        // 1) Every complete base must be inside the battlefield.
        foreach (ModelToken model
            in joined)
        {
            if (model == null ||
                !model.IsAlive)
            {
                continue;
            }

            if (!InsideBoard(
                    model,
                    model.transform.position))
            {
                failureReason =
                    model.RoleName +
                    " is outside the battlefield";
                return false;
            }
        }

        // 2) Every complete base must be wholly within the active
        // mission deployment polygon.
        MissionDeploymentZone zone =
            DeploymentZoneForFaction(
                faction
            );

        if (zone == null)
        {
            failureReason =
                "no mission deployment zone is configured";
            return false;
        }

        foreach (ModelToken model
            in joined)
        {
            if (model == null ||
                !model.IsAlive)
            {
                continue;
            }

            if (!zone.ContainsBase(
                    model.transform.position,
                    model.BaseRadiusInches))
            {
                failureReason =
                    model.RoleName +
                    " is not wholly inside the " +
                    (activeMissionBattlefield != null
                        ? activeMissionBattlefield
                            .DisplayName
                        : "mission") +
                    " deployment zone";
                return false;
            }
        }

        // 3) Members of the same Attached Unit are checked once against
        // each other. They are NOT sent through CanPlaceModel, because that
        // generic method sees the Bodyguard and Leader as two SquadController
        // objects and can therefore treat members of the same joined unit as
        // battlefield blockers.
        for (int i = 0;
             i < joined.Count;
             i++)
        {
            ModelToken first =
                joined[i];

            if (first == null ||
                !first.IsAlive)
            {
                continue;
            }

            for (int j = i + 1;
                 j < joined.Count;
                 j++)
            {
                ModelToken second =
                    joined[j];

                if (second == null ||
                    !second.IsAlive)
                {
                    continue;
                }

                float required =
                    MinimumModelSeparation(
                        first,
                        second
                    );

                float actual =
                    HorizontalDistance(
                        first.transform.position,
                        second.transform.position
                    );

                if (actual <
                    required - 0.015f)
                {
                    failureReason =
                        "two models in the Attached Unit overlap (" +
                        first.RoleName +
                        " / " +
                        second.RoleName +
                        ")";
                    return false;
                }
            }
        }

        HashSet<ModelToken> joinedSet =
            new HashSet<ModelToken>(
                joined.Where(
                    model =>
                        model != null
                )
            );

        // 4) Only OTHER deployed units are external blockers.
        foreach (ModelToken model
            in joined)
        {
            if (model == null ||
                !model.IsAlive)
            {
                continue;
            }

            foreach (SquadController squad
                in squads)
            {
                if (squad == null ||
                    !squad.IsOnBattlefield)
                {
                    continue;
                }

                foreach (ModelToken other
                    in squad.LivingModelTokens())
                {
                    if (other == null ||
                        !other.IsAlive ||
                        joinedSet.Contains(
                            other
                        ))
                    {
                        continue;
                    }

                    if (HorizontalDistance(
                            model.transform.position,
                            other.transform.position
                        ) <
                        MinimumModelSeparation(
                            model,
                            other
                        ) -
                        0.015f)
                    {
                        failureReason =
                            model.RoleName +
                            " overlaps deployed unit " +
                            squad.DisplayName;
                        return false;
                    }
                }
            }

            if (ModelOverlapsBlockingTerrain(
                    model,
                    model.transform.position))
            {
                failureReason =
                    model.RoleName +
                    " overlaps blocking terrain";
                return false;
            }
        }

        // 5) Coherency is evaluated last on the completed joined formation.
        if (!bodyguard.IsCoherent())
        {
            failureReason =
                "the generated Bodyguard + Leader formation is not coherent";
            return false;
        }

        return true;
    }

    private List<Vector3>
        BuildDeploymentCentreCandidates(
            Vector3 requested,
            float minX,
            float maxX,
            float minZ,
            float maxZ)
    {
        List<Vector3> result =
            new List<Vector3>();

        result.Add(
            requested
        );

        float[] distances =
        {
            0.75f,
            1.5f,
            2.5f,
            4.0f,
            6.0f,
            8.0f,
            10.0f,
            14.0f
        };

        foreach (float distance
            in distances)
        {
            for (int angle = 0;
                 angle < 360;
                 angle += 15)
            {
                float radians =
                    angle *
                    Mathf.Deg2Rad;

                Vector3 candidate =
                    requested +
                    new Vector3(
                        Mathf.Cos(radians) *
                            distance,
                        0f,
                        Mathf.Sin(radians) *
                            distance
                    );

                candidate.x =
                    Mathf.Clamp(
                        candidate.x,
                        minX,
                        maxX
                    );

                candidate.z =
                    Mathf.Clamp(
                        candidate.z,
                        minZ,
                        maxZ
                    );

                bool duplicate =
                    result.Any(
                        existing =>
                            HorizontalDistance(
                                existing,
                                candidate
                            ) <
                            0.05f
                    );

                if (!duplicate)
                {
                    result.Add(
                        candidate
                    );
                }
            }
        }

        // Polygon maps can have legal pockets that are not reachable by a
        // short radial search from the click. Add a coarse whole-battlefield
        // fallback, then keep candidates ordered by distance from the user's
        // requested point.
        for (float x = minX;
             x <= maxX + 0.001f;
             x += 3.0f)
        {
            for (float z = minZ;
                 z <= maxZ + 0.001f;
                 z += 3.0f)
            {
                Vector3 candidate =
                    new Vector3(
                        x,
                        0f,
                        z
                    );

                if (!result.Any(
                    existing =>
                        HorizontalDistance(
                            existing,
                            candidate
                        ) <
                        0.10f))
                {
                    result.Add(
                        candidate
                    );
                }
            }
        }

        return result
            .OrderBy(
                candidate =>
                    HorizontalDistance(
                        requested,
                        candidate
                    )
            )
            .ToList();
    }

    private void RestoreFailedJoinedDeployment(
        SquadController bodyguard,
        SquadController leader,
        Vector3 oldBodyRoot,
        Vector3 oldLeaderRoot,
        Dictionary<ModelToken, Vector3>
            oldLocalPositions)
    {
        bodyguard.StageForDeployment();
        leader.StageForDeployment();

        bodyguard.transform.position =
            oldBodyRoot;

        leader.transform.position =
            oldLeaderRoot;

        foreach (
            KeyValuePair<
                ModelToken,
                Vector3
            > pair
            in oldLocalPositions)
        {
            if (pair.Key != null)
            {
                pair.Key
                    .transform.localPosition =
                    pair.Value;
            }
        }

        Physics.SyncTransforms();
    }

    private bool DeploymentLocationLegal(
        SquadController squad,
        string faction)
    {
        if (SquadFitsDeploymentZone(
                squad,
                faction))
        {
            return true;
        }

        bool infiltrators =
            UniversalRuleRegistry.UnitHasRule(
                squad,
                "Infiltrators"
            );

        if (squad.AttachedLeader != null)
        {
            infiltrators =
                infiltrators &&
                UniversalRuleRegistry.UnitHasRule(
                    squad.AttachedLeader,
                    "Infiltrators"
                );
        }

        if (!infiltrators)
            return false;

        if (activeMissionBattlefield == null)
            return false;

        string opponentFaction =
            factions.FirstOrDefault(
                value =>
                    value != faction
            );

        MissionDeploymentZone opponentZone =
            DeploymentZoneForFaction(
                opponentFaction
            );

        if (opponentZone == null)
            return false;

        foreach (ModelToken model
            in JoinedModels(squad))
        {
            if (model == null)
                continue;

            float distanceToOpponentZone =
                opponentZone.DistanceToZone(
                    model.transform.position
                ) -
                model.BaseRadiusInches;

            if (distanceToOpponentZone <=
                8.0f + 0.001f)
            {
                return false;
            }

            foreach (SquadController enemy
                in squads)
            {
                if (enemy == null ||
                    enemy.FactionId == faction ||
                    !enemy.IsAlive ||
                    !enemy.IsOnBattlefield)
                {
                    continue;
                }

                foreach (ModelToken enemyModel
                    in JoinedModels(enemy))
                {
                    if (HorizontalDistance(
                            model.transform.position,
                            enemyModel.transform.position
                        ) <=
                        8.0f)
                    {
                        return false;
                    }
                }
            }
        }

        return true;
    }

    private bool SquadFitsDeploymentZone(
        SquadController squad,
        string faction)
    {
        if (squad == null)
            return false;

        MissionDeploymentZone zone =
            DeploymentZoneForFaction(
                faction
            );

        if (zone == null)
        {
            // Custom/open-war fallback.
            float boardMin =
                -BoardWidth * 0.5f;

            float boardMax =
                BoardWidth * 0.5f;

            float minX;
            float maxX;

            if (factions.Count > 0 &&
                faction == factions[0])
            {
                minX = boardMin;
                maxX =
                    boardMin +
                    DeploymentZoneWidth;
            }
            else
            {
                minX =
                    boardMax -
                    DeploymentZoneWidth;

                maxX = boardMax;
            }

            foreach (ModelToken model
                in JoinedModels(squad))
            {
                float radius =
                    model != null
                    ? model.BaseRadiusInches
                    : 0f;

                if (model.transform.position.x -
                        radius <
                        minX - 0.001f ||
                    model.transform.position.x +
                        radius >
                        maxX + 0.001f)
                {
                    return false;
                }
            }

            return true;
        }

        foreach (ModelToken model
            in JoinedModels(squad))
        {
            if (model == null)
                continue;

            if (!zone.ContainsBase(
                    model.transform.position,
                    model.BaseRadiusInches))
            {
                return false;
            }
        }

        return true;
    }

    private List<SquadController>
        CompatibleDeploymentBodyguards()
    {
        if (currentDeploymentSquad == null ||
            !currentDeploymentSquad.IsLeaderUnit)
        {
            return new List<SquadController>();
        }

        return squads
            .Where(
                squad =>
                    squad.IsAlive &&
                    squad.BattlefieldState !=
                        SquadBattlefieldState.Reserves &&
                    currentDeploymentSquad
                        .CanAttachTo(squad)
            )
            .ToList();
    }

    private SquadController
        CurrentDeploymentBodyguardTarget()
    {
        List<SquadController> candidates =
            CompatibleDeploymentBodyguards();

        if (candidates.Count == 0)
            return null;

        deploymentBodyguardChoiceIndex =
            Mathf.Clamp(
                deploymentBodyguardChoiceIndex,
                0,
                candidates.Count - 1
            );

        return candidates[
            deploymentBodyguardChoiceIndex
        ];
    }

    private void CycleDeploymentBodyguardTarget()
    {
        List<SquadController> candidates =
            CompatibleDeploymentBodyguards();

        if (candidates.Count <= 1)
            return;

        deploymentBodyguardChoiceIndex =
            (deploymentBodyguardChoiceIndex + 1) %
            candidates.Count;

        SquadController target =
            candidates[
                deploymentBodyguardChoiceIndex
            ];

        status =
            "Selected bodyguard for " +
            currentDeploymentSquad.DisplayName +
            ": " +
            target.DisplayName +
            ".";
    }

    private bool LeaderDeploymentCandidateIsLegal(
        SquadController leader,
        SquadController bodyguard,
        ModelToken leaderModel)
    {
        if (leader == null ||
            bodyguard == null ||
            leaderModel == null)
        {
            return false;
        }

        if (!InsideBoard(
                leaderModel.transform.position))
        {
            return false;
        }

        // The joined unit must remain wholly in the correct deployment zone.
        // Use the bodyguard's faction because it is the unit currently being
        // deployed; this avoids any display-faction naming differences on
        // imported Leader datasheets.
        if (!SquadFitsDeploymentZone(
                bodyguard,
                bodyguard.FactionId))
        {
            return false;
        }

        // The Leader itself must not overlap any already deployed model or
        // blocking terrain. CanPlaceModel deliberately ignores off-board
        // undeployed/reserve units as of v26.7.
        if (!CanPlaceModel(
                leaderModel,
                leaderModel.transform.position))
        {
            return false;
        }

        float nearestBodyguard =
            bodyguard.LivingModelTokens()
                .Min(
                    model =>
                        HorizontalDistance(
                            leaderModel.transform.position,
                            model.transform.position
                        )
                );

        if (nearestBodyguard >
            2.0f + 0.001f)
        {
            return false;
        }

        // Validate coherency only after the physical/zone checks. This uses
        // the joined bodyguard+Leader model list because the attachment is
        // already established before deployment.
        if (!bodyguard.IsCoherent())
        {
            return false;
        }

        return true;
    }

    private void SendCurrentDeploymentToReserves()
    {
        if (!deploymentMode ||
            currentDeploymentSquad == null)
        {
            return;
        }

        SquadController reserved =
            currentDeploymentSquad;

        reserved.SendToReserves();

        if (reserved.AttachedLeader != null)
        {
            reserved.AttachedLeader
                .SendToReserves();
        }

        currentDeploymentSquad = null;

        status =
            reserved.DisplayName +
            " placed in Reserves.";

        AdvanceDeploymentTurn();
    }

    private List<SquadController> ActiveFactionReserves()
    {
        return squads
            .Where(
                squad =>
                    squad.FactionId ==
                        activeFaction &&
                    !squad.IsAttachedLeader &&
                    squad.IsInReserves &&
                    squad.IsAlive
            )
            .ToList();
    }

    private int EffectiveReserveRound(
        SquadController unit)
    {
        return
            round +
            (aeldariRules != null &&
             aeldariRules
                .TreatReserveRoundAsOneHigher(
                    unit
                )
                ? 1
                : 0);
    }

    private bool ReserveCanArriveThisRound(
        SquadController unit)
    {
        if (reservePlacementSquad != null &&
            CurrentRoundNumber == 1 &&
            CustodesFactionPack11.CanIngressFirstMovement(reservePlacementSquad))
        {
            return true;
        }


        if (unit == null)
            return false;

        return
            unit.MustIngressFromVeil ||
            EffectiveReserveRound(
                unit
            ) >= 2;
    }

    private void CycleReservePlacement()
    {
        if (deploymentMode)
            return;

        if (phase != Phase.Move)
        {
            status =
                "Reserves can only arrive in the Move phase.";
            return;
        }

        List<SquadController> available =
            ActiveFactionReserves()
                .Where(
                    unit =>
                        ReserveCanArriveThisRound(
                            unit
                        )
                )
                .ToList();

        if (available.Count == 0)
        {
            reservePlacementSquad = null;
            status =
                activeFaction +
                " has no units waiting in Reserves.";
            return;
        }

        reserveCycleIndex =
            (reserveCycleIndex + 1) %
            available.Count;

        reservePlacementSquad =
            available[
                reserveCycleIndex
            ];

        string method =
            reservePlacementSquad.HasDeepStrike
            ? "DEEP STRIKE: place anywhere on the board, more than 8 from every enemy model."
            : "STRATEGIC RESERVE: place within 6 of a board edge and more than 8 from every enemy model.";

        status =
            "Reserve selected: " +
            reservePlacementSquad.DisplayName +
            ". " +
            method +
            " Click the board to attempt placement.";
    }

    private bool TryPlaceAttachedLeaderAfterReserveArrival(
        SquadController bodyguard)
    {
        if (bodyguard == null ||
            bodyguard.AttachedLeader == null ||
            !bodyguard.AttachedLeader.IsAlive)
        {
            return true;
        }

        SquadController leader =
            bodyguard.AttachedLeader;

        List<ModelToken> bodyModels =
            bodyguard.LivingModelTokens();

        if (bodyModels.Count == 0)
            return false;

        ModelToken leaderModel =
            leader.LivingModelTokens()
                .FirstOrDefault();

        if (leaderModel == null)
            return false;

        foreach (ModelToken anchor
            in bodyModels)
        {
            float leaderSpacing =
                MinimumModelSeparation(
                    anchor,
                    leaderModel
                ) +
                0.06f;

            for (int angle = 0;
                 angle < 360;
                 angle += 30)
            {
                float radians =
                    angle *
                    Mathf.Deg2Rad;

                Vector3 candidate =
                    anchor.transform.position +
                    new Vector3(
                        Mathf.Cos(radians) *
                            leaderSpacing,
                        0f,
                        Mathf.Sin(radians) *
                            leaderSpacing
                    );

                leader.DeployToBattlefield(
                    candidate
                );

                Physics.SyncTransforms();

                bool legal =
                    leader.IsCoherent() &&
                    AllModelsInsideBoard(leader) &&
                    AllModelsHaveLegalPlacement(leader) &&
                    leader.DistanceTo(bodyguard) <=
                        2.05f &&
                    ReserveEnemyDistanceIsLegal(
                        leader
                    ) &&
                    ReserveRoundDeploymentZoneIsLegal(
                        leader
                    ) &&
                    (bodyguard.HasDeepStrike ||
                     StrategicReserveEdgeIsLegal(
                        leader
                     ));

                if (legal)
                    return true;

                leader.SendToReserves();
            }
        }

        return false;
    }

    private void TryPlaceReserveSquad(
        Vector3 destination)
    {
        if (reservePlacementSquad == null ||
            phase != Phase.Move ||
            !ReserveCanArriveThisRound(
                reservePlacementSquad))
        {
            return;
        }

        SquadController squad =
            reservePlacementSquad;

        Vector3 oldRoot =
            squad.transform.position;

        destination.y = 0f;

        squad.DeployToBattlefield(
            destination
        );

        Physics.SyncTransforms();

        bool legal =
            AllModelsInsideBoard(squad) &&
            AllModelsHaveLegalPlacement(squad) &&
            squad.IsCoherent() &&
            ReserveEnemyDistanceIsLegal(squad) &&
            ReserveRoundDeploymentZoneIsLegal(
                squad
            );

        if (legal &&
            !squad.HasDeepStrike)
        {
            legal =
                StrategicReserveEdgeIsLegal(
                    squad
                );
        }

        if (legal &&
            squad.AttachedLeader != null)
        {
            legal =
                TryPlaceAttachedLeaderAfterReserveArrival(
                    squad
                );
        }

        if (!legal)
        {
            squad.SendToReserves();

            if (squad.AttachedLeader != null)
                squad.AttachedLeader.SendToReserves();

            squad.transform.position =
                oldRoot;

            status =
                squad.HasDeepStrike
                ? "Illegal Deep Strike position: stay on-board, avoid collisions, and remain more than 8 from enemy models."
                : "Illegal Strategic Reserve position: unit must be within 6 of a board edge and more than 8 from enemy models.";
            return;
        }

        squad.HasMoved = true;
        squad.MarkSetUpThisTurn();
        NotifyUnitSetUp(squad);
        squad.MustIngressFromVeil = false;
        squad.TemporaryDeepStrike = false;

        if (squad.AttachedLeader != null)
        {
            squad.AttachedLeader.MustIngressFromVeil = false;
            squad.AttachedLeader.TemporaryDeepStrike = false;
        }

        reservePlacementSquad = null;
        reserveCycleIndex = -1;

        status =
            squad.DisplayName +
            (squad.HasDeepStrike
                ? " arrived by Deep Strike."
                : " arrived from Strategic Reserves.") +
            " It counts as having moved.";
    }

    private bool ReserveRoundDeploymentZoneIsLegal(
        SquadController squad)
    {
        if (squad == null ||
            EffectiveReserveRound(
                squad
            ) >= 3 ||
            squad.HasDeepStrike)
        {
            return true;
        }

        string opponent =
            factions.FirstOrDefault(
                faction =>
                    faction !=
                        squad.FactionId
            );

        MissionDeploymentZone opponentZone =
            DeploymentZoneForFaction(
                opponent
            );

        if (opponentZone == null)
            return true;

        foreach (ModelToken model
            in JoinedModels(squad))
        {
            if (model != null &&
                opponentZone.ContainsBase(
                    model.transform.position,
                    model.BaseRadiusInches))
            {
                return false;
            }
        }

        return true;
    }

    private bool ReserveEnemyDistanceIsLegal(
        SquadController arriving)
    {
        foreach (ModelToken model
            in arriving.LivingModelTokens())
        {
            foreach (SquadController enemySquad
                in squads)
            {
                if (!enemySquad.IsOnBattlefield ||
                    enemySquad.FactionId ==
                        arriving.FactionId ||
                    !enemySquad.IsAlive)
                {
                    continue;
                }

                foreach (ModelToken enemy
                    in enemySquad.LivingModelTokens())
                {
                    if (HorizontalDistance(
                            model.transform.position,
                            enemy.transform.position
                        ) <=
                        ReserveEnemyExclusionDistance)
                    {
                        return false;
                    }
                }
            }
        }

        return true;
    }

    private bool StrategicReserveEdgeIsLegal(
        SquadController squad)
    {
        float halfWidth =
            BoardWidth * 0.5f;

        float halfDepth =
            BoardDepth * 0.5f;

        foreach (ModelToken model
            in JoinedModels(squad))
        {
            Vector3 position =
                model.transform.position;

            float radius =
                model != null
                ? model.BaseRadiusInches
                : 0f;

            float xEdgeDistance =
                halfWidth -
                Mathf.Abs(position.x) -
                radius;

            float zEdgeDistance =
                halfDepth -
                Mathf.Abs(position.z) -
                radius;

            float distanceToEdge =
                Mathf.Min(
                    xEdgeDistance,
                    zEdgeDistance
                );

            if (distanceToEdge >
                StrategicReserveEdgeDistance +
                0.001f)
            {
                return false;
            }
        }

        return true;
    }

    public bool MissionPositionInEitherDeploymentZone(
        Vector3 position)
    {
        if (activeMissionBattlefield == null)
            return false;

        Vector2 point =
            new Vector2(
                position.x,
                position.z
            );

        return
            (activeMissionBattlefield
                 .AttackerZone != null &&
             activeMissionBattlefield
                 .AttackerZone
                 .ContainsPoint(point)) ||
            (activeMissionBattlefield
                 .DefenderZone != null &&
             activeMissionBattlefield
                 .DefenderZone
                 .ContainsPoint(point));
    }

    public string[] WorldUiReserveEntries(
        int index)
    {
        return ReserveBoxEntries(
            WorldUiFactionId(
                index
            )
        ).ToArray();
    }

    private List<string> ReserveBoxEntries(
        string faction)
    {
        List<string> entries =
            new List<string>();

        foreach (SquadController squad
            in squads)
        {
            if (squad == null ||
                squad.FactionId !=
                    faction ||
                !squad.IsAlive ||
                !squad.IsInReserves ||
                squad.IsAttachedLeader)
            {
                continue;
            }

            string entry =
                squad.DisplayName +
                " [" +
                squad.LivingModels +
                "/" +
                squad.StartingModels +
                "]";

            if (squad.AttachedLeader != null &&
                squad.AttachedLeader.IsAlive &&
                squad.AttachedLeader.IsInReserves)
            {
                entry +=
                    " + " +
                    squad.AttachedLeader.DisplayName;
            }

            entries.Add(entry);
        }

        return entries;
    }

}
