using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.Networking;

// Generated by the Warboard v35 structural refactor.
// Method bodies were moved verbatim from GameController.cs.
public partial class GameController : MonoBehaviour
{
    private void OfferFightOnDeath(
        InteractiveAttackController resolvedAttack)
    {
        SquadController target =
            resolvedAttack.Target != null
            ? resolvedAttack.Target.JoinedActionController()
            : null;

        if (target == null)
        {
            ContinuePostAttackFlow();
            return;
        }

        List<ModelToken> candidates =
            new List<ModelToken>();

        foreach (ModelToken model
            in resolvedAttack.DestroyedModels)
        {
            if (model == null ||
                model.Squad == null)
            {
                continue;
            }

            DestroyedModelRecord record =
                destroyedModelsThisPhase
                    .LastOrDefault(
                        item =>
                            item != null &&
                            item.Model == model
                    );

            if (record != null &&
                record.HadFought)
            {
                continue;
            }

            bool parting =
                target.PartingTheVeilActive &&
                target.HasKeyword("ynnari");

            bool malevolentSouls =
                UniversalRuleRegistry.UnitHasRule(
                    model.Squad,
                    "Malevolent Souls"
                );

            if (parting)
            {
                candidates.Add(model);
                continue;
            }

            if (malevolentSouls)
            {
                int roll =
                    DiceRoller.RollD6(
                        "Malevolent Souls: " +
                        target.DisplayName
                    );

                if (roll >= 3)
                    candidates.Add(model);
            }
        }

        if (candidates.Count == 0)
        {
            ContinuePostAttackFlow();
            return;
        }

        List<WeaponAttackSelection> selections =
            BuildFightOnDeathSelections(
                candidates
            );

        if (selections.Count == 0 ||
            resolvedAttack.Attacker == null ||
            !resolvedAttack.Attacker.IsAlive)
        {
            ContinuePostAttackFlow();
            return;
        }

        OpenRuleChoice(
            "FIGHT ON DEATH",
            candidates.Count +
            " destroyed model(s) can fight after the attacking unit finishes.",
            new[]
            {
                new RuleChoiceOption(
                    "Resolve fight-on-death attacks",
                    () =>
                    {
                        CloseRuleChoice();

                        interactiveAttackCompletionCallback =
                            ContinuePostAttackFlow;

                        interactiveAttackConsumesNormalAction =
                            false;
                        interactiveAttackSuppressesPostReactions =
                            true;

                        BeginInteractiveAttack(
                            target,
                            resolvedAttack.Attacker,
                            selections,
                            AttackMode.Melee,
                            false
                        );
                    }
                ),
                new RuleChoiceOption(
                    "Skip fight-on-death attacks",
                    () =>
                    {
                        CloseRuleChoice();
                        ContinuePostAttackFlow();
                    }
                )
            }
        );
    }

    private List<WeaponAttackSelection>
        BuildFightOnDeathSelections(
            List<ModelToken> models)
    {
        List<WeaponAttackSelection> result =
            new List<WeaponAttackSelection>();

        foreach (ModelToken model
            in models)
        {
            if (model == null)
                continue;

            List<WeaponData> weapons =
                model.MeleeWeapons
                    .Where(
                        weapon =>
                            weapon != null
                    )
                    .ToList();

            WeaponData normal =
                weapons.FirstOrDefault(
                    weapon =>
                        !WeaponRuleParser.Has(
                            weapon,
                            "extra_attacks")
                );

            if (normal != null)
            {
                result.Add(
                    new WeaponAttackSelection(
                        model,
                        normal
                    )
                );
            }

            foreach (WeaponData extra
                in weapons.Where(
                    weapon =>
                        WeaponRuleParser.Has(
                            weapon,
                            "extra_attacks")
                ))
            {
                result.Add(
                    new WeaponAttackSelection(
                        model,
                        extra
                    )
                );
            }
        }

        return result;
    }

    private void BeginFightPhaseFlow()
    {
        fightEligibleAtStart.Clear();
        heraldOfYnneadTarget = null;
        heraldOfYnneadFaction = "";

        foreach (SquadController unit
            in squads)
        {
            if (unit == null ||
                unit.IsAttachedLeader ||
                !unit.IsAlive ||
                !unit.IsOnBattlefield)
            {
                continue;
            }

            if (IsEngaged(unit))
            {
                fightEligibleAtStart.Add(
                    unit.JoinedActionController()
                );
            }
        }

        if (OfferHeraldOfYnnead())
            return;

        OfferLethalReprisal();
    }

    private void BeginFightSequence()
    {
        Fight11BeginPileInStep();
    }

    private bool UnitHasFightsFirst(
        SquadController unit)
    {
        if (unit == null)
            return false;

        SquadController actionUnit =
            unit.JoinedActionController();

        return
            actionUnit.MadeChargeMove ||
            actionUnit.TemporaryFightsFirst ||
            FactionRuleSystem.UnitOrLeaderHasRule(
                actionUnit,
                "Fights First"
            );
    }

    private bool IsEligibleToFightNow(
        SquadController unit)
    {
        return Fight11IsEligibleToFightNow(unit);
    }

    private List<SquadController> EligibleFightUnits(
        string faction,
        bool fightsFirstOnly)
    {
        return Fight11EligibleFightUnits(faction, fightsFirstOnly);
    }

    private bool AnyEligibleFightUnits()
    {
        return Fight11AnyEligibleFightUnits();
    }

    private void ResolveFightSelector(
        string preferredFaction)
    {
        Fight11ResolveFightSelector(preferredFaction);
    }

    private void AdvanceFightPriority(
        SquadController unitThatFought)
    {
        Fight11AdvanceFightPriority(unitThatFought);
    }

    private string FightPriorityText()
    {
        return Fight11FightPriorityText();
    }

    private void ExecuteFight(
        SquadController attacker,
        SquadController target)
    {
        BeginFightActivation(
            attacker,
            target
        );
    }

    private bool ModelBelongsToFightActivation(
        ModelToken model)
    {
        return
            model != null &&
            model.IsAlive &&
            model.Squad != null &&
            fightActivationUnit != null &&
            model.Squad
                .JoinedActionController() ==
                fightActivationUnit;
    }

    private float FightStageMoveLimit()
    {
        if (fightActivationUnit == null)
            return 0f;

        return
            fightActivationUnit
                .SuddenStrikeActive
            ? 6f
            : (fightActivationStage ==
                    FightActivationStage.PileIn
                ? PileInDistance
                : ConsolidateDistance);
    }

    private void CaptureFightStageStartPositions()
    {
        fightStageStartPositions.Clear();
        fightStageMovedModels.Clear();

        if (fightActivationUnit == null)
            return;

        foreach (ModelToken model
            in JoinedModels(
                fightActivationUnit))
        {
            if (model == null ||
                !model.IsAlive)
            {
                continue;
            }

            fightStageStartPositions[
                model] =
                model.transform.position;
        }
    }

    private bool FightStageDestinationLegal(
        ModelToken model,
        Vector3 destination,
        out string reason)
    {
        return Fight11FightStageDestinationLegal(model, destination, out reason);
    }

    private void TryFightStageMoveSelectedModel(
        Vector3 destination)
    {
        if (selectedModel == null ||
            !ModelBelongsToFightActivation(
                selectedModel))
        {
            status =
                "Select a model from the active fighting unit first.";
            return;
        }

        string reason;

        if (!FightStageDestinationLegal(
                selectedModel,
                destination,
                out reason))
        {
            status = reason;
            return;
        }

        selectedModel.transform.position =
            new Vector3(
                destination.x,
                selectedModel
                    .transform.position.y,
                destination.z
            );

        Physics.SyncTransforms();

        fightStageMovedModels.Add(
            selectedModel
        );

        fightActivationUnit.RefreshVisuals();

        if (fightActivationUnit.AttachedLeader != null)
        {
            fightActivationUnit
                .AttachedLeader
                .RefreshVisuals();
        }

        RefreshObjectiveDisplays();
        RefreshMoveRing();

        Vector3 start =
            fightStageStartPositions
                .ContainsKey(
                    selectedModel)
            ? fightStageStartPositions[
                selectedModel]
            : selectedModel.transform.position;

        float distance =
            HorizontalDistance(
                start,
                selectedModel
                    .transform.position
            );

        status =
            selectedModel.RoleName +
            " " +
            (fightActivationStage ==
                FightActivationStage.PileIn
                ? "piled in "
                : "consolidated ") +
            distance.ToString("0.0") +
            "″.";
    }

    private void BeginFightActivation(
        SquadController attacker,
        SquadController target)
    {
        Fight11BeginNormalFight(attacker, target, false);
    }

    private void ClearFightModelFocus()
    {
        if (fightActivationUnit == null)
            return;

        fightActivationUnit.FocusModel(
            null
        );

        if (fightActivationUnit.AttachedLeader != null)
        {
            fightActivationUnit
                .AttachedLeader
                .FocusModel(
                    null
                );
        }
    }

    private void CompleteFightPileIn()
    {
        Fight11CompletePileIn();
    }

    private List<ModelToken>
        FightPotentialAttackModels()
    {
        if (fightActivationUnit == null)
        {
            return new List<ModelToken>();
        }

        return
            JoinedModels(
                fightActivationUnit)
                .Where(
                    model =>
                        model != null &&
                        model.IsAlive &&
                        model.MeleeWeapons.Count > 0
                )
                .ToList();
    }

    private List<WeaponData>
        DistinctMeleeWeapons(
            ModelToken model,
            bool extraAttacks)
    {
        if (model == null)
        {
            return new List<WeaponData>();
        }

        return
            model.MeleeWeapons
                .Where(
                    weapon =>
                        weapon != null &&
                        model.CanUseWeapon(
                            weapon) &&
                        WeaponRuleParser.Has(
                            weapon,
                            "extra_attacks") ==
                        extraAttacks
                )
                .GroupBy(
                    weapon =>
                        !string.IsNullOrWhiteSpace(
                            weapon.id)
                        ? weapon.id
                        : weapon.displayName
                )
                .Select(
                    group =>
                        group.First()
                )
                .ToList();
    }

    private List<WeaponAttackSelection>
        BuildFightModelSelections(
            ModelToken model,
            WeaponData selectedNormal)
    {
        List<WeaponAttackSelection> result =
            new List<WeaponAttackSelection>();

        if (model == null)
            return result;

        if (selectedNormal != null)
        {
            result.Add(
                new WeaponAttackSelection(
                    model,
                    selectedNormal
                )
            );
        }

        foreach (WeaponData extra
            in DistinctMeleeWeapons(
                model,
                true))
        {
            result.Add(
                new WeaponAttackSelection(
                    model,
                    extra
                )
            );
        }

        return result;
    }

    private string MeleeWeaponProfileText(
        WeaponData weapon)
    {
        if (weapon == null)
            return "Unknown melee weapon";

        string attacks =
            string.IsNullOrWhiteSpace(
                weapon.attacksExpression)
            ? weapon.attacksPerModel
                .ToString()
            : weapon.attacksExpression;

        string damage =
            string.IsNullOrWhiteSpace(
                weapon.damageExpression)
            ? weapon.damage.ToString()
            : weapon.damageExpression;

        return
            weapon.displayName +
            "   |   A " +
            attacks +
            "   |   WS " +
            weapon.skill +
            "+   |   S " +
            weapon.strength +
            "   |   AP " +
            weapon.ap +
            "   |   D " +
            damage;
    }

    private void PrepareFightModelWeaponSelection(
        ModelToken model)
    {
        fightPreparedAttackModel = null;
        fightPreparedMeleeWeapon = null;

        if (fightActivationStage !=
                FightActivationStage.Attacks ||
            !ModelBelongsToFightActivation(
                model))
        {
            return;
        }

        if (fightModelsResolvedThisActivation
            .Contains(
                model))
        {
            status =
                model.RoleName +
                " has already resolved its melee attacks this activation.";
            return;
        }

        List<WeaponData> normal =
            DistinctMeleeWeapons(
                model,
                false
            );

        List<WeaponData> extras =
            DistinctMeleeWeapons(
                model,
                true
            );

        if (normal.Count == 0 &&
            extras.Count == 0)
        {
            status =
                model.RoleName +
                " has no usable melee weapon.";
            return;
        }

        fightPreparedAttackModel =
            model;

        if (normal.Count == 0)
        {
            status =
                model.RoleName +
                " has only [EXTRA ATTACKS] profiles. Click an enemy target.";

            RefreshMoveRing();
            return;
        }

        if (normal.Count == 1)
        {
            fightPreparedMeleeWeapon =
                normal[0];

            status =
                model.RoleName +
                "  ->  " +
                normal[0].displayName +
                ". Click an enemy target.";

            RefreshMoveRing();
            return;
        }

        List<RuleChoiceOption> options =
            new List<RuleChoiceOption>();

        foreach (WeaponData weapon
            in normal)
        {
            WeaponData captured =
                weapon;

            options.Add(
                new RuleChoiceOption(
                    MeleeWeaponProfileText(
                        captured
                    ),
                    () =>
                    {
                        CloseRuleChoice();

                        fightPreparedAttackModel =
                            model;

                        fightPreparedMeleeWeapon =
                            captured;

                        status =
                            model.RoleName +
                            "  ->  " +
                            captured.displayName +
                            ". Click an enemy target.";

                        RefreshMoveRing();
                    }
                )
            );
        }

        OpenRuleChoice(
            "SELECT MELEE WEAPON  -  " +
            model.RoleName,
            "Choose this model's normal melee profile. Any [EXTRA ATTACKS] profiles are added automatically. Then click the enemy target.",
            options.ToArray()
        );
    }

    private void TryFightModelAttack(
        ModelToken model,
        SquadController target)
    {
        if (fightActivationStage !=
                FightActivationStage.Attacks ||
            fightActivationUnit == null ||
            !ModelBelongsToFightActivation(
                model))
        {
            status =
                "No model-level melee attack is currently available.";
            return;
        }

        if (fightModelsResolvedThisActivation
            .Contains(
                model))
        {
            status =
                model.RoleName +
                " has already resolved or skipped its attacks this activation.";
            return;
        }

        if (target == null ||
            !target.IsAlive ||
            !target.IsOnBattlefield ||
            target.FactionId ==
                fightActivationUnit.FactionId)
        {
            status =
                "Select an enemy unit as this model's melee target.";
            return;
        }

        float distance =
            ModelDistanceToSquad(
                model,
                target
            );

        if (distance >
            EngagementRange +
            0.05f)
        {
            status =
                model.RoleName +
                " is " +
                distance.ToString("0.0") +
                "″ from that unit and is not in melee range.";
            return;
        }

        if (fightPreparedAttackModel !=
            model)
        {
            PrepareFightModelWeaponSelection(
                model
            );

            status =
                model.RoleName +
                " needs a melee weapon/profile selected before choosing a target.";
            return;
        }

        StartFightModelWeaponAttack(
            model,
            target,
            fightPreparedMeleeWeapon
        );
    }

    private void StartFightModelWeaponAttack(
        ModelToken model,
        SquadController target,
        WeaponData selectedNormal)
    {
        if (!ModelBelongsToFightActivation(
                model) ||
            target == null)
        {
            return;
        }

        if (OfferAeldariPathOfWarrior(
                fightActivationUnit,
                () =>
                    StartFightModelWeaponAttack(
                        model,
                        target,
                        selectedNormal
                    )))
        {
            return;
        }

        List<WeaponAttackSelection> selections =
            BuildFightModelSelections(
                model,
                selectedNormal
            );

        fightPreparedAttackModel = null;
        fightPreparedMeleeWeapon = null;

        if (selections.Count == 0)
        {
            status =
                model.RoleName +
                " has no melee attack profiles to resolve.";
            return;
        }

        interactiveAttackConsumesNormalAction =
            false;

        interactiveAttackCompletionCallback =
            () =>
                CompleteFightModelAttack(
                    model
                );

        BeginInteractiveAttack(
            fightActivationUnit,
            target,
            selections,
            AttackMode.Melee,
            false
        );
    }

    private void CompleteFightModelAttack(
        ModelToken model)
    {
        Fight11CompleteFightModelAttack(model);
    }

    private void SkipSelectedFightModel()
    {
        Fight11SkipSelectedFightModel();
    }

    private void CompleteFightAttacks()
    {
        Fight11CompleteFightAttacks();
    }

    private void BeginFightConsolidation()
    {
        Fight11FinishSelectedFightAttacks();
    }

    private void CompleteFightConsolidation()
    {
        Fight11CompleteConsolidation();
    }

    private void ClearFightActivationState()
    {
        fightActivationStage =
            FightActivationStage.None;

        fightActivationUnit = null;
        fightActivationInitialTarget = null;
        fightPreparedAttackModel = null;
        fightPreparedMeleeWeapon = null;

        fightModelsResolvedThisActivation.Clear();
        fightStageMovedModels.Clear();
        fightStageStartPositions.Clear();

        ClearSelectionVisualOnly();

        selectedSquad = null;
        selectedModel = null;
        wholeSquadMoveMode = false;

        HideMovementCursorMeasure();
        RefreshMoveRing();
    }

    private void TryFight(
        SquadController attacker,
        SquadController target)
    {
        string custodesTargetReason;
        if (attacker != null && target != null &&
            !Custodes11CanAttackTarget(
                attacker, target, AttackMode.Melee,
                out custodesTargetReason))
        {
            status = custodesTargetReason;
            return;
        }

        if (attacker != null && target != null &&
            Custodes11EnsureKatahChoice(attacker, target))
        {
            return;
        }


        Fight11TryFight(attacker, target);
    }

    private List<WeaponAttackSelection>
        GetEligibleMeleeWeapons(
            SquadController attacker,
            SquadController target)
    {
        List<WeaponAttackSelection> result =
            new List<WeaponAttackSelection>();

        foreach (ModelToken model
            in JoinedModels(attacker))
        {
            float distance =
                ModelDistanceToSquad(
                    model,
                    target
                );

            if (distance >
                EngagementRange +
                0.05f)
            {
                continue;
            }

            List<WeaponData> weapons =
                model.MeleeWeapons
                    .Where(
                        weapon =>
                            weapon != null
                    )
                    .ToList();

            if (weapons.Count == 0)
                continue;

            // Extra Attacks profiles are made in addition to the one normal
            // melee weapon the model selects.
            List<WeaponData> extraAttacks =
                weapons
                    .Where(
                        weapon =>
                            RulesEngine.HasKeyword(
                                weapon,
                                "extra_attacks"
                            )
                    )
                    .GroupBy(
                        weapon =>
                            weapon.id ??
                            weapon.displayName
                    )
                    .Select(
                        group =>
                            group.First()
                    )
                    .ToList();

            List<WeaponData> normalWeapons =
                weapons
                    .Where(
                        weapon =>
                            !RulesEngine.HasKeyword(
                                weapon,
                                "extra_attacks"
                            )
                    )
                    .GroupBy(
                        weapon =>
                            weapon.id ??
                            weapon.displayName
                    )
                    .Select(
                        group =>
                            group.First()
                    )
                    .ToList();

            WeaponData selectedNormal =
                normalWeapons
                    .OrderByDescending(
                        weapon =>
                            EstimateMeleeWeaponValue(
                                model,
                                target,
                                weapon
                            )
                    )
                    .FirstOrDefault();

            if (selectedNormal != null)
            {
                result.Add(
                    new WeaponAttackSelection(
                        model,
                        selectedNormal
                    )
                );
            }

            foreach (WeaponData weapon
                in extraAttacks)
            {
                result.Add(
                    new WeaponAttackSelection(
                        model,
                        weapon
                    )
                );
            }

            // Edge case: a data source presents only an Extra Attacks profile.
            if (selectedNormal == null &&
                extraAttacks.Count == 0)
            {
                WeaponData fallback =
                    weapons.FirstOrDefault();

                if (fallback != null)
                {
                    result.Add(
                        new WeaponAttackSelection(
                            model,
                            fallback
                        )
                    );
                }
            }
        }

        return result;
    }

    private float EstimateMeleeWeaponValue(
        ModelToken model,
        SquadController target,
        WeaponData weapon)
    {
        if (weapon == null)
            return 0f;

        SquadController attackOwner =
            model.Squad != null
            ? model.Squad
            : selectedSquad;

        int skill =
            attackOwner != null
            ? attackOwner.GetMeleeSkill(
                target,
                weapon
              )
            : Mathf.Clamp(
                weapon.skill,
                2,
                6
              );

        float hitChance =
            Mathf.Clamp01(
                (7f - skill) /
                6f
            );

        int woundNeeded =
            RulesEngine.WoundRollNeeded(
                weapon.strength,
                target.Toughness
            );

        float woundChance =
            Mathf.Clamp01(
                (7f - woundNeeded) /
                6f
            );

        int saveNeeded =
            Mathf.Clamp(
                target.GetSave(
                    attackOwner
                ) -
                weapon.ap,
                2,
                7
            );

        float failedSaveChance =
            saveNeeded >= 7
            ? 1f
            : Mathf.Clamp01(
                (saveNeeded - 1f) /
                6f
              );

        float averageAttacks =
            RulesEngine.AverageCharacteristic(
                weapon.attacksExpression,
                weapon.attacksPerModel
            );

        float averageDamage =
            RulesEngine.AverageCharacteristic(
                weapon.damageExpression,
                weapon.damage
            );

        if (RulesEngine.HasKeyword(
            weapon,
            "torrent"))
        {
            hitChance = 1f;
        }

        return
            averageAttacks *
            hitChance *
            woundChance *
            failedSaveChance *
            averageDamage;
    }

}
